# Copyright (C) 2023 Adam McKellar
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


services:
  transcoder:
    build: 
      dockerfile: ./transcoder.dockerfile
    depends_on:
      - web
      - db
    environment:
      - WEBTRANS_POSTGRES_URL=postgres://postgres:changeme@db:5432/postgres
      - WEBTRANS_PYTHON_EXECUTABLE_PATH=python3
      - WEBTRANS_PYTHON_SCRIPT=/opt/TransCoder/translate.py
      - WEBTRANS_MODEL_1=/opt/models/model_1.pth
      - WEBTRANS_MODEL_2=/opt/models/model_2.pth
    command: /opt/background_runner/bin/background_runner
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    build:
      dockerfile: ./webui.dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:changeme@db:5432/postgres
      - API_KEY=
      - SUPPORT_EMAIL=
      - SEND_GRID_KEY=unused
      - LUCKY_ENV=production
      - SECRET_KEY_BASE=changeme1234changeme1234changeme1234
      - APP_DOMAIN=example.com
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 8085:80
    command: /srv/webui/start_webui
    
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  pgdata:

